backend:
  name: git-gateway
media_folder: static/assets
public_folder: /assets
collections:
  - name: home-page
    label: Home Page
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: hero
        label: Hero
        file: _site/home-page/hero.json
        description: Hero Settings
        fields:
          - {label: Title, name: hero_title, widget: text}
          - {label: Subtitle, name: hero_subtitle, widget: text}
      - name: services
        label: Services
        file: _site/home-page/services.json
        description: Services
        fields:
          - {label: Title, name: services_title, widget: string}
          - {label: Description, name: services_description, widget: text}
          - label: "Services"
            name: "services_primary_list"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Description, name: description, widget: text}
          - {label: Description, name: services_sub_description, widget: text}
          - label: "Secondary Services"
            name: "services_secondary_list"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Description, name: description, widget: text}
  - name: page
    label: Pages
    label_singular: Page
    folder: _site/pages
    create: true
    fields:
      - { name: title, label: Page title }
      - { name: seoTitle, label: SEO Page title, widget: string }
      - { name: seoDescription, label: SEO Description, widget: text }
      - name: template
        label: Page template
        widget: select
        options:
          - { label: Default, value: page }
      - { name: body, label: Page content, widget: markdown }
  - name: projects
    label: Projects
    label_singular: Project
    folder: _site/projects
    create: true
    fields:
      - { name: title, label: Project title }
      - { name: seoTitle, label: SEO Project title, widget: string }
      - { name: seoDescription, label: SEO Description, widget: text }
      - name: template
        label: Page template
        widget: select
        options:
          - { label: Default, value: project }
      - { name: body, label: Page content, widget: markdown }
      