backend:
  name: git-gateway
media_folder: static/assets
public_folder: /assets
collections:
  - name: home-page
    label: Home Page
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: hero
        label: Hero
        file: _site/home-page/hero.json
        description: Hero Settings
        fields:
          - {label: Title, name: title, widget: text}
          - {label: Subtitle, name: subtitle, widget: text}
      - name: services
        label: Services
        file: _site/home-page/services.json
        description: Services
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - label: "Services"
            name: "primaryList"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Description, name: description, widget: text}
          - {label: Description, name: subDescription, widget: text}
          - label: Secondary Services
            name: secondaryList
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Description, name: description, widget: text}
      - name: projects
        label: Projects
        file: _site/home-page/projects.json
        description: Projects
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - label: Featured Projects
            name: featuredProjects
            widget: "list"
            fields:
            - label: Project
              name: project
              widget: relation
              collection: projects
              displayFields: ["title"]
              searchFields: ["title", "body"]
              valueField: title
      - name: contacts
        label: Contacts
        file: _site/home-page/contacts.json
        description: Contancts
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
         
  - name: page
    label: Pages
    label_singular: Page
    folder: _site/pages
    create: true
    fields:
      - { name: title, label: Page title }
      - { name: seoTitle, label: SEO Page title, widget: string }
      - { name: seoDescription, label: SEO Description, widget: text }
      - name: template
        label: Page template
        widget: select
        options:
          - { label: Default, value: page }
      - { name: body, label: Page content, widget: markdown }
  - name: projects
    label: Projects
    label_singular: Project
    folder: _site/projects
    create: true
    fields:
      - { name: title, label: Project title }
      - { name: seoTitle, label: SEO Project title, widget: string }
      - { name: seoDescription, label: SEO Description, widget: text }
      - { name: excerpt, label: Excerpt, widget: text }
      - { name: featuredImage, label: Featured image, widget: image }
      - { name: logo, label: Logo, widget: image }
      - name: template
        label: Page template
        widget: select
        options:
          - { label: Default, value: project }
      - { name: body, label: Page content, widget: markdown }
     
      