backend:
  name: git-gateway
media_folder: static/assets
public_folder: /assets
collections:
  - name: page
    label: Pages
    label_singular: Page
    folder: _site/pages
    create: true
    fields:
      - { name: title, label: Page title }
      - name: template
        label: Page template
        widget: select
        options:
          - { label: Default, value: default-page }
          - { label: Documents, value: documents-page }
      - { name: body, label: Page content, widget: "markdown" }
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Hero"
        file: "_site/home-page/hero.json"
        description: "Hero Settings"
        fields:
          - {label: "Title", name: "hero_title", widget: "text"}
          - {label: "Subtitle", name: "hero_subtitle", widget: "text"}
      