backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: static-pages
    label: Static Pages
    delete: false
    files:
      - name: home
        label: Home Page
        file: "_site/static-pages/home.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: home
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
              - label: Hero
                name: hero
                widget: object
                fields:
                  - { label: Title, name: title, widget: text }
                  - { label: Subtitle, name: subtitle, widget: text }
              - label: Services
                name: services
                widget: list
                fields:
                  - { label: Group Title, name: groupTitle, widget: string }
                  - {
                      label: Group Description,
                      name: groupDescription,
                      widget: text,
                    }
                  - label: Services group
                    name: "serviceList"
                    widget: "list"
                    fields:
                      - { label: Title, name: title, widget: string }
                      - { label: Image, name: image, widget: image }
                      - { label: Description, name: description, widget: text }
                      - { label: Link, name: link, widget: string }
              - label: Projects
                name: projects
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Description, name: description, widget: text }
                  - label: Featured Projects
                    name: featuredProjects
                    widget: list
                    fields:
                      - label: Project
                        name: project
                        widget: relation
                        collection: projects
                        displayFields: ["title"]
                        searchFields: ["title", "body"]
                        valueField: title
              - label: Contacts
                name: contacts
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Description, name: description, widget: text }
      - name: projects
        label: Projects Page
        file: "_site/static-pages/projects.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: projects
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
      - name: blog
        label: Blog Page
        file: "_site/static-pages/blog.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: blog
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
      - name: contacts
        label: Contacts Page
        file: "_site/static-pages/contacts.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: contacts
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
              - { label: Intro, name: intro, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
      - name: services
        label: Services Page
        file: "_site/static-pages/services.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: contacts
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
              - { label: Intro, name: intro, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
              - label: Services List
                name: servicesList
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Image, name: image, widget: image }
                  - { label: Description, name: description, widget: markdown }
                  - label: Points
                    name: points
                    widget: list
                    fields:
                      - { label: Title, name: title, widget: markdown }
      - name: privacy
        label: Privacy Page
        file: "_site/static-pages/privacy.json"
        fields:
          - label: Template
            name: template
            widget: hidden
            default: privacy
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - { label: Title, name: title, widget: string }
              - { label: Path, name: path, widget: string, default: / }
              - label: SEO
                name: seo
                widget: object
                fields:
                  - { label: SEO Description, name: description, widget: text }
                  - { label: Image, name: image, widget: image }
              - { label: Intro, name: intro, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
  - label: Pages
    label_singular: Page
    name: page
    folder: _site/pages
    create: true
    fields:
      - { name: title, label: Page title }
      - label: Page template
        name: template
        widget: select
        options:
          - { label: Default, value: page }
      - label: Locales
        name: locales
        widget: list
        fields:
          - label: Language
            name: language
            widget: select
            options:
              - { label: English, value: en }
              - { label: Italian, value: it }
          - label: Page handle
            name: handle
            widget: string
            required: false
          - label: SEO
            name: seo
            widget: object
            fields:
              - { name: title, label: SEO title, widget: string }
              - { name: description, label: SEO Description, widget: text }
          - { name: body, label: Page content, widget: markdown }
  - label: Projects
    label_singular: Project
    name: projects
    folder: _site/projects
    create: true
    fields:
      - { name: title, label: Project title }
      - label: Page template
        name: template
        widget: select
        options:
          - { label: Default, value: project }
      - label: "Priority"
        name: "priority"
        widget: "select"
        default: "0"
        options:
          - { label: "Lowest", value: "5" }
          - { label: "Low", value: "4" }
          - { label: "Medium", value: "3" }
          - { label: "High", value: "2" }
          - { label: "Higher", value: "1" }
          - { label: "Highest", value: "0" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - label: Locales
        name: locales
        widget: list
        fields:
          - label: Language
            name: language
            widget: select
            options:
              - { label: English, value: en }
              - { label: Italian, value: it }
          - { name: seoTitle, label: SEO Project title, widget: string }
          - { name: seoDescription, label: SEO Description, widget: text }
          - { name: excerpt, label: Excerpt, widget: text }
          - { name: type, label: Type Project, widget: string }
          - { name: featuredImage, label: Featured image, widget: image }
          - { name: heroImage, label: Hero image, widget: image }
          - { name: body, label: Page content, widget: markdown }
  - label: Posts
    label_singular: Post
    name: posts
    folder: _site/posts
    create: true
    fields:
      - { name: title, label: Project title }
      - label: Page template
        name: template
        widget: select
        options:
          - { label: Default, value: blog }
      - label: "Priority"
        name: "priority"
        widget: "select"
        default: "0"
        options:
          - { label: "Lowest", value: "5" }
          - { label: "Low", value: "4" }
          - { label: "Medium", value: "3" }
          - { label: "High", value: "2" }
          - { label: "Higher", value: "1" }
          - { label: "Highest", value: "0" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }

      - label: Locales
        name: locales
        widget: list
        fields:
          - label: Language
            name: language
            widget: select
            options:
              - { label: English, value: en }
              - { label: Italian, value: it }
          - { name: seoTitle, label: SEO Project title, widget: string }
          - { name: seoDescription, label: SEO Description, widget: text }
          - { name: excerpt, label: Excerpt, widget: text }
          - { name: author, label: Author, widget: string }
          - {
              name: date,
              label: Date,
              widget: date,
              default: "",
              format: "DD-MM-YYYY",
            }
          - { name: featuredImage, label: Featured image, widget: image }
          - { name: heroImage, label: Hero image, widget: image }
          - { name: body, label: Page content, widget: markdown }
  - label: Settings
    name: settings
    delete: false
    files:
      - label: General
        name: general
        file: "_site/settings/general.json"
        fields:
          - label: Default language
            name: defaultLanguage
            widget: select
            default: en
            options:
              - { label: English, value: en }
              - { label: Italian, value: it }
      - label: Contacts
        name: contacts
        file: "_site/settings/contacts.json"
        fields:
          - { label: Email, name: email, widget: string }
          - label: Socials
            name: socials
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Icon Handle, name: iconHandle, widget: string }

      - label: Navigation
        name: navigation
        file: "_site/settings/navigation.json"
        fields:
          - label: Locales
            name: locales
            widget: list
            fields:
              - label: Language
                name: language
                widget: select
                default: en
                options:
                  - { label: English, value: en }
                  - { label: Italian, value: it }
              - label: Main navigation
                name: main
                widget: object
                fields:
                  - label: Links
                    name: links
                    widget: list
                    fields:
                      - label: Label
                        name: label
                      - label: URL
                        name: url
